### ISSUE TITLE
Stop using deprecated repository tikui

### ISSUE THREAD

**Issue by hdurix** [tikui/tikui.org#36]
Following #32 and #34, we should not use readme of the [deprecated repository](https://github.com/tikui/tikui).

See [here](https://github.com/tikui/tikui.org/blob/main/src/get-started.pug#L68)

Instead 2 other options:
- https://github.com/tikui/tikui.org#tutorial (we have to keep it up to date)
- https://github.com/tikui/tikui-cli/tree/main/src/cli/generate-project/common#tutorial (up to date but technical resource for generation)

Which one is best? Is there third option?

> Same for other deprecated repo `tikui` uses (4 others)

**Comment by Gnuk** [comment]
Maybe the more living option is to link the generated README.md or to say we need to follow the tutorial with the generated README.md
